name: CI
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
      - name: Release
        run: |
          npm install
          npx semantic-release

